### ISSUE TITLE
Hosting solution for dockerized es-api

### ISSUE THREAD

**Issue by lwm** [lwm/es-api#6]
Since closing down the Heroku app (very slow, complicated Docker plugin setup). 

It is now necessary to find a new, cheap solution for hosting this app.

**Comment by lwm** [comment]
On a quick check, this looks good - https://cloud.docker.com/account/

**Comment by blueyed** [comment]
Also check out RHC: https://www.openshift.com/

**Comment by lwm** [comment]
> Also check out RHC: https://www.openshift.com/

The data to be imported exceeds the free tier, however, they were very kind to allow me to run it off the 'Online Resource Grants program'. 

Thanks for the recommendation!
